// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rowsum_dir_Mat
arma::vec rowsum_dir_Mat(arma::mat M);
RcppExport SEXP _ergmclust_rowsum_dir_Mat(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(rowsum_dir_Mat(M));
    return rcpp_result_gen;
END_RCPP
}
// colsum_dir_Mat
arma::vec colsum_dir_Mat(arma::mat M);
RcppExport SEXP _ergmclust_colsum_dir_Mat(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(colsum_dir_Mat(M));
    return rcpp_result_gen;
END_RCPP
}
// gamma_update_HMM_stat_dir
arma::cube gamma_update_HMM_stat_dir(arma::mat gamma, arma::vec pi, arma::mat theta, arma::mat network, int N, int K);
RcppExport SEXP _ergmclust_gamma_update_HMM_stat_dir(SEXP gammaSEXP, SEXP piSEXP, SEXP thetaSEXP, SEXP networkSEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pi(piSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type network(networkSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(gamma_update_HMM_stat_dir(gamma, pi, theta, network, N, K));
    return rcpp_result_gen;
END_RCPP
}
// grad_HMM_stat_dir_oe
arma::vec grad_HMM_stat_dir_oe(arma::mat theta, arma::mat gamma, arma::mat network, int N, int K);
RcppExport SEXP _ergmclust_grad_HMM_stat_dir_oe(SEXP thetaSEXP, SEXP gammaSEXP, SEXP networkSEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type network(networkSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_HMM_stat_dir_oe(theta, gamma, network, N, K));
    return rcpp_result_gen;
END_RCPP
}
// grad_HMM_stat_dir_re
arma::vec grad_HMM_stat_dir_re(arma::mat theta, arma::mat gamma, arma::mat network, int N, int K);
RcppExport SEXP _ergmclust_grad_HMM_stat_dir_re(SEXP thetaSEXP, SEXP gammaSEXP, SEXP networkSEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type network(networkSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_HMM_stat_dir_re(theta, gamma, network, N, K));
    return rcpp_result_gen;
END_RCPP
}
// hess_HMM_stat_dir_oe
arma::mat hess_HMM_stat_dir_oe(arma::mat theta, arma::mat gamma, int N, int K);
RcppExport SEXP _ergmclust_hess_HMM_stat_dir_oe(SEXP thetaSEXP, SEXP gammaSEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(hess_HMM_stat_dir_oe(theta, gamma, N, K));
    return rcpp_result_gen;
END_RCPP
}
// hess_HMM_stat_dir_re
arma::mat hess_HMM_stat_dir_re(arma::mat theta, arma::mat gamma, int N, int K);
RcppExport SEXP _ergmclust_hess_HMM_stat_dir_re(SEXP thetaSEXP, SEXP gammaSEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(hess_HMM_stat_dir_re(theta, gamma, N, K));
    return rcpp_result_gen;
END_RCPP
}
// hess_HMM_stat_dir_oe_re
arma::mat hess_HMM_stat_dir_oe_re(arma::mat theta, arma::mat gamma, int N, int K);
RcppExport SEXP _ergmclust_hess_HMM_stat_dir_oe_re(SEXP thetaSEXP, SEXP gammaSEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(hess_HMM_stat_dir_oe_re(theta, gamma, N, K));
    return rcpp_result_gen;
END_RCPP
}
// ELBO_conv_HMM_stat_dir
float ELBO_conv_HMM_stat_dir(arma::mat gamma, arma::vec alpha, arma::mat theta, arma::mat network, int N, int K);
RcppExport SEXP _ergmclust_ELBO_conv_HMM_stat_dir(SEXP gammaSEXP, SEXP alphaSEXP, SEXP thetaSEXP, SEXP networkSEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type network(networkSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(ELBO_conv_HMM_stat_dir(gamma, alpha, theta, network, N, K));
    return rcpp_result_gen;
END_RCPP
}
// grad_HMM_stat_dir_oe_K1
float grad_HMM_stat_dir_oe_K1(arma::vec theta, arma::mat network, int N);
RcppExport SEXP _ergmclust_grad_HMM_stat_dir_oe_K1(SEXP thetaSEXP, SEXP networkSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type network(networkSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_HMM_stat_dir_oe_K1(theta, network, N));
    return rcpp_result_gen;
END_RCPP
}
// grad_HMM_stat_dir_re_K1
float grad_HMM_stat_dir_re_K1(arma::vec theta, arma::mat network, int N);
RcppExport SEXP _ergmclust_grad_HMM_stat_dir_re_K1(SEXP thetaSEXP, SEXP networkSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type network(networkSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_HMM_stat_dir_re_K1(theta, network, N));
    return rcpp_result_gen;
END_RCPP
}
// hess_HMM_stat_dir_oe_K1
float hess_HMM_stat_dir_oe_K1(arma::vec theta, int N);
RcppExport SEXP _ergmclust_hess_HMM_stat_dir_oe_K1(SEXP thetaSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(hess_HMM_stat_dir_oe_K1(theta, N));
    return rcpp_result_gen;
END_RCPP
}
// hess_HMM_stat_dir_re_K1
float hess_HMM_stat_dir_re_K1(arma::vec theta, int N);
RcppExport SEXP _ergmclust_hess_HMM_stat_dir_re_K1(SEXP thetaSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(hess_HMM_stat_dir_re_K1(theta, N));
    return rcpp_result_gen;
END_RCPP
}
// hess_HMM_stat_dir_oe_re_K1
float hess_HMM_stat_dir_oe_re_K1(arma::vec theta, int N);
RcppExport SEXP _ergmclust_hess_HMM_stat_dir_oe_re_K1(SEXP thetaSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(hess_HMM_stat_dir_oe_re_K1(theta, N));
    return rcpp_result_gen;
END_RCPP
}
// ELBO_conv_HMM_stat_dir_K1
float ELBO_conv_HMM_stat_dir_K1(arma::vec theta, arma::mat network, int N);
RcppExport SEXP _ergmclust_ELBO_conv_HMM_stat_dir_K1(SEXP thetaSEXP, SEXP networkSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type network(networkSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(ELBO_conv_HMM_stat_dir_K1(theta, network, N));
    return rcpp_result_gen;
END_RCPP
}
// rowsum_Mat
arma::vec rowsum_Mat(arma::mat M);
RcppExport SEXP _ergmclust_rowsum_Mat(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(rowsum_Mat(M));
    return rcpp_result_gen;
END_RCPP
}
// colsum_Mat
arma::vec colsum_Mat(arma::mat M);
RcppExport SEXP _ergmclust_colsum_Mat(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(colsum_Mat(M));
    return rcpp_result_gen;
END_RCPP
}
// gamma_update_HMM_stat_undir
arma::cube gamma_update_HMM_stat_undir(arma::mat gamma, arma::vec pi, arma::vec theta, arma::mat network, int N, int K);
RcppExport SEXP _ergmclust_gamma_update_HMM_stat_undir(SEXP gammaSEXP, SEXP piSEXP, SEXP thetaSEXP, SEXP networkSEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pi(piSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type network(networkSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(gamma_update_HMM_stat_undir(gamma, pi, theta, network, N, K));
    return rcpp_result_gen;
END_RCPP
}
// grad_HMM_stat_undir
arma::mat grad_HMM_stat_undir(arma::vec theta, arma::mat gamma, arma::mat network, int N, int K);
RcppExport SEXP _ergmclust_grad_HMM_stat_undir(SEXP thetaSEXP, SEXP gammaSEXP, SEXP networkSEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type network(networkSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_HMM_stat_undir(theta, gamma, network, N, K));
    return rcpp_result_gen;
END_RCPP
}
// hess_HMM_stat_undir
arma::mat hess_HMM_stat_undir(arma::vec theta, arma::mat gamma, int N, int K);
RcppExport SEXP _ergmclust_hess_HMM_stat_undir(SEXP thetaSEXP, SEXP gammaSEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(hess_HMM_stat_undir(theta, gamma, N, K));
    return rcpp_result_gen;
END_RCPP
}
// ELBO_conv_HMM_stat_undir
float ELBO_conv_HMM_stat_undir(arma::mat gamma, arma::vec pi, arma::vec theta, arma::mat network, int N, int K);
RcppExport SEXP _ergmclust_ELBO_conv_HMM_stat_undir(SEXP gammaSEXP, SEXP piSEXP, SEXP thetaSEXP, SEXP networkSEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pi(piSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type network(networkSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(ELBO_conv_HMM_stat_undir(gamma, pi, theta, network, N, K));
    return rcpp_result_gen;
END_RCPP
}
// grad_HMM_stat_undir_K1
float grad_HMM_stat_undir_K1(float theta, arma::mat network, int N);
RcppExport SEXP _ergmclust_grad_HMM_stat_undir_K1(SEXP thetaSEXP, SEXP networkSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type network(networkSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_HMM_stat_undir_K1(theta, network, N));
    return rcpp_result_gen;
END_RCPP
}
// hess_HMM_stat_undir_K1
float hess_HMM_stat_undir_K1(float theta, int N);
RcppExport SEXP _ergmclust_hess_HMM_stat_undir_K1(SEXP thetaSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(hess_HMM_stat_undir_K1(theta, N));
    return rcpp_result_gen;
END_RCPP
}
// ELBO_conv_HMM_stat_undir_K1
float ELBO_conv_HMM_stat_undir_K1(float theta, arma::mat network, int N);
RcppExport SEXP _ergmclust_ELBO_conv_HMM_stat_undir_K1(SEXP thetaSEXP, SEXP networkSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type network(networkSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(ELBO_conv_HMM_stat_undir_K1(theta, network, N));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ergmclust_rowsum_dir_Mat", (DL_FUNC) &_ergmclust_rowsum_dir_Mat, 1},
    {"_ergmclust_colsum_dir_Mat", (DL_FUNC) &_ergmclust_colsum_dir_Mat, 1},
    {"_ergmclust_gamma_update_HMM_stat_dir", (DL_FUNC) &_ergmclust_gamma_update_HMM_stat_dir, 6},
    {"_ergmclust_grad_HMM_stat_dir_oe", (DL_FUNC) &_ergmclust_grad_HMM_stat_dir_oe, 5},
    {"_ergmclust_grad_HMM_stat_dir_re", (DL_FUNC) &_ergmclust_grad_HMM_stat_dir_re, 5},
    {"_ergmclust_hess_HMM_stat_dir_oe", (DL_FUNC) &_ergmclust_hess_HMM_stat_dir_oe, 4},
    {"_ergmclust_hess_HMM_stat_dir_re", (DL_FUNC) &_ergmclust_hess_HMM_stat_dir_re, 4},
    {"_ergmclust_hess_HMM_stat_dir_oe_re", (DL_FUNC) &_ergmclust_hess_HMM_stat_dir_oe_re, 4},
    {"_ergmclust_ELBO_conv_HMM_stat_dir", (DL_FUNC) &_ergmclust_ELBO_conv_HMM_stat_dir, 6},
    {"_ergmclust_grad_HMM_stat_dir_oe_K1", (DL_FUNC) &_ergmclust_grad_HMM_stat_dir_oe_K1, 3},
    {"_ergmclust_grad_HMM_stat_dir_re_K1", (DL_FUNC) &_ergmclust_grad_HMM_stat_dir_re_K1, 3},
    {"_ergmclust_hess_HMM_stat_dir_oe_K1", (DL_FUNC) &_ergmclust_hess_HMM_stat_dir_oe_K1, 2},
    {"_ergmclust_hess_HMM_stat_dir_re_K1", (DL_FUNC) &_ergmclust_hess_HMM_stat_dir_re_K1, 2},
    {"_ergmclust_hess_HMM_stat_dir_oe_re_K1", (DL_FUNC) &_ergmclust_hess_HMM_stat_dir_oe_re_K1, 2},
    {"_ergmclust_ELBO_conv_HMM_stat_dir_K1", (DL_FUNC) &_ergmclust_ELBO_conv_HMM_stat_dir_K1, 3},
    {"_ergmclust_rowsum_Mat", (DL_FUNC) &_ergmclust_rowsum_Mat, 1},
    {"_ergmclust_colsum_Mat", (DL_FUNC) &_ergmclust_colsum_Mat, 1},
    {"_ergmclust_gamma_update_HMM_stat_undir", (DL_FUNC) &_ergmclust_gamma_update_HMM_stat_undir, 6},
    {"_ergmclust_grad_HMM_stat_undir", (DL_FUNC) &_ergmclust_grad_HMM_stat_undir, 5},
    {"_ergmclust_hess_HMM_stat_undir", (DL_FUNC) &_ergmclust_hess_HMM_stat_undir, 4},
    {"_ergmclust_ELBO_conv_HMM_stat_undir", (DL_FUNC) &_ergmclust_ELBO_conv_HMM_stat_undir, 6},
    {"_ergmclust_grad_HMM_stat_undir_K1", (DL_FUNC) &_ergmclust_grad_HMM_stat_undir_K1, 3},
    {"_ergmclust_hess_HMM_stat_undir_K1", (DL_FUNC) &_ergmclust_hess_HMM_stat_undir_K1, 2},
    {"_ergmclust_ELBO_conv_HMM_stat_undir_K1", (DL_FUNC) &_ergmclust_ELBO_conv_HMM_stat_undir_K1, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ergmclust(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
